name: Street Art
favicon: null
layout_spectrum: 0.3649678654037416
typography_spectrum: 0.29417783208191395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-3413653-7
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5998047110624611
purpose: []
